### Loaded
import os
import json
import pandas as pd

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

with open(BASE_DIR + '/adcode.json', 'r', encoding='utf8') as f: ADCODE = json.load(f)
ADCODE_DF = pd.read_csv(BASE_DIR + '/adcode.csv')

### App
# APPID = 'wx951ebae14616ad9a'
# APPSECRET = '2cba46ee43add4aeca979aedef92bd24'
APPID = 'wxd3b8c5438a79609d'
APPSECRET = 'ab2dc811bb5f830308d66ff489b049eb'
OPENID_LEN = 128
SERVER_IP = '114.116.197.121'
SERVER_HOSTNAME = 'tra-fr-2.zhouyc.cc'
SERVER_PORT = 443

APP_SHOW_STATUS = False

### Utilities
## UUID
DEFAULT_NAMESPACE = 'db5acd0b317f474f82d0294722786034'
IMAGE_NAMESPACE = '04814d8c269b465cab37423163984ba0'

## JWT
JWT_EXPIRE_SECONDS = 60 * 60 * 24

## Permission
SUPER_USER_ID = -2
ADMIN_USER_ID = -1
ANONYMOUS_USER_ID = 0
USER_JWT_HEADER_NAME = 'token-auth'
USER_JWT_KEY = '958bfcfd62d236249b443a2283b0c51a'

### Admin
ADMIN_USERNAME = 'admin'
ADMIN_PASSWORD = 'dwOftI4yo8J22614'
ADMIN_ACCESS_TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjozMjUzNjg1MDM5OSwianRpIjoiVGhpcyB0b2tlbiBpcyBtYW51YWxseSBjcmVhdGVkLiIsInVzZXJfaWQiOjF9.4Xne0Jk3n_wUYIiDPHKLjj69RoXEKcx5fOTWk3xRSe0'

### App
## Models
# Images
MAX_IMAGE_DESCRIPTION_LEN = 200

# Recommend
RECOMMEND_DECAY_PARAM1 = -0.27621943
RECOMMEND_DECAY_PARAM2 = -0.91748966

RECOMMEND_LIKE_AMOUNT = 100

RECOMMEND_PCA_DIMENSIONS = 16
RECOMMEND_CLUSTER_RATIO = 0.0001
RECOMMEND_CLUSTER_MINIMUM = 8

# AppUser
MAX_USER_NAME_LEN = 20
MAX_USER_REALNAME_LEN = 10
MAX_USER_SIGN_LEN = 140
MAX_USER_PASSWORD_LEN = 64
MAX_USER_EMAIL_LEN = 40
MAX_USER_PHONE_LEN = 30

USER_ID_NAMESPACE = '2318d637c663305c8cd06f6144c60b01'

GENDERS = {
    0: 'Unknown',
    1: 'Male',
    2: 'Female',
}
GENDERS_DEFAULT = 0

USER_DEFAULT_LEVEL = 1


# Position
COUNTRIES = {
    0: '',
}
COUNTRIES_DEFAULT = 0

PROVINCES = {
    0: '',
}
PROVINCES_DEFAULT = 0

CITIES = {
    0: '',
}
CITIES_DEFAULT = 0

DISTRICTS = {
    0: '',
}
DISTRICTS_DEFAULT = 0

MAX_POSITION_POSTAL_CODE_LENGTH = 6

POSITION_RECOMMEND_AMOUNT = 3
POSITION_RECOMMEND_MAX_AMOUNT = 20
POSITION_RECOMMEND_TRUNCATE = 16

# Travel
MAX_TRAVEL_TITLE_LENGTH = 40
MAX_TRAVEL_CONTENT_LENGTH = 20000

TRAVEL_VISIBILITIES_ALL = 0
TRAVEL_VISIBILITIES_PRIVATE = 1

TRAVEL_VISIBILITIES = {
    TRAVEL_VISIBILITIES_ALL: 'All',
    TRAVEL_VISIBILITIES_PRIVATE: 'Private',
}
TRAVEL_VISIBILITIES_DEFAULT = 0

TRAVEL_FORBIDDEN_FALSE = 0
TRAVEL_FORBIDDEN_TRUE = 1
TRAVEL_FORBIDDEN_PENDING = 2

TRAVEL_LIST_MODE_TIME = 0
TRAVEL_LIST_MODE_HEAT = 1
TRAVEL_LIST_MODE_RECOMMEND = 2

TRAVEL_LIST_MODES = {
    TRAVEL_LIST_MODE_TIME,
    TRAVEL_LIST_MODE_HEAT,
    TRAVEL_LIST_MODE_RECOMMEND,
}
TRAVEL_LIST_MODE_DEFAULT = TRAVEL_LIST_MODE_TIME

TRAVEL_HEAT_READ_RECORD = 30

TRAVEL_HEAT_WEIGHT_RECENT = 1
TRAVEL_HEAT_WEIGHT_COLLECTIONS = 50
TRAVEL_HEAT_WEIGHT_LIKES = 10
TRAVEL_HEAT_WEIGHT_COMMENTS = 100

TRAVEL_RECOMMEND_DEFAULT_AMOUNT = 20
TRAVEL_RECOMMEND_MAX_AMOUNT = 20

TRAVEL_RECOMMEND_EXCEED_RATE = 2.0
TRAVEL_RECOMMEND_CLUSTER_WEIGHT = 0.6
TRAVEL_RECOMMEND_USER_WEIGHT = 0.3
TRAVEL_RECOMMEND_HEAT_WEIGHT = 0.1

TRAVEL_SIMILAR_AMOUNT = 3
TRAVEL_SIMILAR_MAX_AMOUNT = 20

# Comment
MAX_COMMENT_CONTENT_LENGTH = 400
COMMENT_TYPE_TRAVEL = 0
COMMENT_TYPE_COMPANION = 1

COMMENT_DELETED_CONTENT = '该评论已删除'

# Message
MAX_MESSAGE_CONTENT_LENGTH = 400

MESSAGE_TYPE_SYSTEM = 0
MESSAGE_TYPE_LIKE_TRAVEL = 1
MESSAGE_TYPE_LIKE_COMMENT = 2
MESSAGE_TYPE_SUBSCRIBE = 3
MESSAGE_TYPE_COMMENT_ON_TRAVEL = 4
MESSAGE_TYPE_COMMENT_ON_COMMENT = 5
MESSAGE_TYPE_COMPANION = 6
MESSAGE_TYPE_COMPANION_QUIT = 7
MESSAGE_TYPE_TRAVEL_FORBIDDEN = 20
MESSAGE_TYPE_COMPANION_FORBIDDEN = 21
MESSAGE_TYPE_TRAVEL_FORBIDDEN_CANCEL = 22
MESSAGE_TYPE_COMPANION_FORBIDDEN_CANCEL = 23

MESSAGE_UNIQUE = {
    MESSAGE_TYPE_LIKE_TRAVEL,
    MESSAGE_TYPE_LIKE_COMMENT,
    MESSAGE_TYPE_SUBSCRIBE,
}

MESSAGE_TYPES_DESCRIPTION = {
    MESSAGE_TYPE_SYSTEM: '有新的通知',
    MESSAGE_TYPE_LIKE_TRAVEL: '点赞了你的游记',
    MESSAGE_TYPE_LIKE_COMMENT: '点赞了你的评论',
    MESSAGE_TYPE_SUBSCRIBE: '关注了你',
    MESSAGE_TYPE_COMMENT_ON_TRAVEL: '评论了你的游记',
    MESSAGE_TYPE_COMMENT_ON_COMMENT: '回复了你',
    MESSAGE_TYPE_COMPANION: '加入了你的同行',
    MESSAGE_TYPE_COMPANION_QUIT: '退出了你的同行',
    MESSAGE_TYPE_TRAVEL_FORBIDDEN: '你的游记未通过审核',
    MESSAGE_TYPE_COMPANION_FORBIDDEN: '你的同行未通过审核',
    MESSAGE_TYPE_TRAVEL_FORBIDDEN_CANCEL: '你的游记已通过审核',
    MESSAGE_TYPE_COMPANION_FORBIDDEN_CANCEL: '你的同行已通过审核',
}
MESSAGE_TYPES_DEFAULT = MESSAGE_TYPE_SYSTEM

# Companion
COMPANION_STATUS_RECRUITING = 0
COMPANION_STATUS_END_RECRUIT = 1
COMPANION_STATUS_STARTED = 2
COMPANION_STATUS_ENDED = 3

COMPANION_REMOVABLE_TIME = 86400 * 3 # 3 days

COMPANION_MAX_CAPACITY = 10000

COMPANION_RECOMMEND_AMOUNT = 3
COMPANION_RECOMMEND_MAX_AMOUNT = 20

# Admin Message
ADMIN_MESSAGE_TIME_LIMIT = 86400

# Report
MAX_REPORT_DESCRIPTION_LENGTH = 100
REPORT_RESULT_PENDING = 0
REPORT_RESULT_SUCCESS = 1
REPORT_RESULT_FAIL = -1

# Traffic
TRAFFIC_FLIGHT = 1
TRAFFIC_TRAIN =  0

# Group
MAX_GROUP_NAME_LENGTH = 20
